### ISSUE TITLE
cannot add multiple increments or timing

### ISSUE THREAD

**Issue by omansour** [BedrockStreaming/StatsdBundle#60]
YAML format doesnt allow it anymore ? 

```
                edge.redirectedto:
                    increment: 'service.service-6play-lbcdn.byedge.<getEdgeHostname>.<getCountryCode>.<getAsn>.edge-redirectedto'
                    increment: 'service.service-6play-lbcdn.bycountry.<getCountryCode>.edge-redirectedto'
                    increment: 'service.service-6play-lbcdn.byasn.<getAsn>.edge-redirectedto'
```

give 

![symfony_profiler](https://user-images.githubusercontent.com/1131098/30649346-51122ec6-9e20-11e7-96b5-c04ef7366b41.png)

**Comment by Oliboy50** [comment]
Indeed, this is not valid YAML and Symfony tends to be more and more "valid YAML compliant" (+ some useful features like using PHP constants, etc.)

From the YAML spec:
> The content of a mapping node is an unordered set of key: value node pairs, with the restriction that each of the keys is unique

I propose to also accept an array of YAML objects (in addition to a single YAML object, to avoid breaking everything), like the following:
```yaml
# new syntax accepting an array of objects
edge.redirectedto:
    - increment: 'service.service-6play-lbcdn.byedge.<getEdgeHostname>.<getCountryCode>.<getAsn>.edge-redirectedto'
    - increment: 'service.service-6play-lbcdn.bycountry.<getCountryCode>.edge-redirectedto'
    - increment: 'service.service-6play-lbcdn.byasn.<getAsn>.edge-redirectedto'

# still possible to use a single object
my_event:
    increment: 'a.metric'
    decrement: 'another.metric'

# new array syntax containing a single object with multiple keys
my_event:
    - 
        increment: 'a.metric'
        decrement: 'another.metric'
```

what do you think?
